name: Netlify Preview Deployments

author: Snaplet

description: Inject instant db url in action

inputs:
  context:
    description: Environment variables
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Set env vars
      shell: bash
      run: CONTEXT="${{ inputs.context }}" node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/env.mjs
