name: Netlify Preview Deployments

author: Snaplet

description: Inject instant db url in action

inputs:
  context:
    description: Environment variables
    required: false
    type: string

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "CONTEXT: ${{ inputs.context }}"
    - name: Set env vars
      shell: bash
      run: node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/env.mjs
