name: Netlify Preview Deployments

author: Snaplet

description: Trigger Netlify to stop Deployments

runs:
  using: composite
  steps:
    - name: Deploy
      shell: bash
      run: "node -e 'process.exit(process.env.CONTEXT === `deploy-preview` ? 0 : 1)'"
