name: Netlify Preview Deployments

author: Snaplet

description: Inject instant db url in action

inputs:
  env:
    description: Environment variables
    required: false
    type: string

runs:
  using: composite
  steps:
    - shell: bash
      run: export DATABASE_URL=${{ inputs.database_url }} CONTEXT=$CONTEXT
    - name: Set env vars
      shell: bash
      run: node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/env.mjs
